export const WISHLIST_LIST_REQUEST = 'WISHLIST_LIST_REQUEST'
export const WISHLIST_LIST_SUCCESS = 'WISHLIST_LIST_SUCCESS'
export const WISHLIST_LIST_FAIL = 'WISHLIST_LIST_FAIL'

export const WISHLIST_ADD_REQUEST = 'WISHLIST_ADD_REQUEST'
export const WISHLIST_ADD_SUCCESS = 'WISHLIST_ADD_SUCCESS'
export const WISHLIST_ADD_FAIL = 'WISHLIST_ADD_FAIL'

export const WISHLIST_DELETE_REQUEST = 'WISHLIST_DELETE_REQUEST'
export const WISHLIST_DELETE_SUCCESS = 'WISHLIST_DELETE_SUCCESS'
export const WISHLIST_DELETE_FAIL = 'WISHLIST_DELETE_FAIL'